### ISSUE TITLE
Build error — TypeError: exps.toString(...).replaceAll is not a function

### ISSUE THREAD

**Issue by mikhail-dvorkin** [tobspr-games/shapez.io#1475]
```
ERROR in ./src/js/core/global_registries.js
Module build failed (from ./gulp/mod.js):
TypeError: exps.toString(...).replaceAll is not a function
    at multiExports (/PATH/shapez.io/gulp/mod.js:12:41)
    at defineFnBody (/PATH/shapez.io/gulp/mod.js:26:20)
    at Object.module.exports (/PATH/shapez.io/gulp/mod.js:36:18)
 @ ./src/js/game/item_registry.js 1:0-58 7:4-17 8:4-17 9:4-17
 @ ./src/js/main.js
 @ multi ./src/js/main.js
```

I receive this error in when running `yarn gulp`. Ubuntu, node v12.22.9, what other info might be helpful to fix?

**Comment by mikhail-dvorkin** [comment]
$ yarn -v
1.22.19

**Comment by EmeraldBlock** [comment]
`replaceAll` is relatively new. Update to Node.js v15 (but not 16; there's a deprecation issue there)

**Comment by dengr1065** [comment]
Closing as stale/missing information.
