### ISSUE TITLE
Failed to build: libgdx.badlogicgames.com has a self-signed certificate

### ISSUE THREAD

**Issue by marek22k** [tobspr-games/shapez.io#1574]
Hello,

I am currently trying to build the game (and play it locally), but without success. I get the following error message:
```
$ yarn gulp
yarn run v1.22.19
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
Please set SHAPEZ_CLI_APPLE_ID
Please set SHAPEZ_CLI_APPLE_CERT_NAME
Please set SHAPEZ_CLI_GITHUB_USER
Please set SHAPEZ_CLI_GITHUB_TOKEN
[21:08:52] Using gulpfile ~/shapez.io/gulp/gulpfile.js
[21:08:52] Starting 'default'...
[21:08:52] Starting 'main.serveDev'...
[21:08:52] Starting 'build.dev'...
[21:08:52] Starting 'utils.cleanup'...
[21:08:52] Starting 'utils.cleanBuildFolder'...
[21:08:52] Finished 'utils.cleanBuildFolder' after 14 ms
[21:08:52] Starting 'utils.cleanImageBuildFolder'...
[21:08:52] Finished 'utils.cleanImageBuildFolder' after 3.21 ms
[21:08:52] Starting 'utils.cleanBuildTempFolder'...
[21:08:52] Finished 'utils.cleanBuildTempFolder' after 2.75 ms
[21:08:52] Finished 'utils.cleanup' after 21 ms
[21:08:52] Starting 'utils.copyAdditionalBuildFiles'...
[21:08:52] Finished 'utils.copyAdditionalBuildFiles' after 4.68 ms
[21:08:52] Starting 'localConfig.findOrCreate'...
[21:08:52] Finished 'localConfig.findOrCreate' after 2.18 ms
[21:08:52] Starting 'imgres.buildAtlas'...
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)
--2023-11-03 21:08:52--  https://libgdx.badlogicgames.com/ci/nightlies/runnables/runnable-texturepacker.jar
Connecting to 127.0.0.1:8118... connected.
ERROR: The certificate of ‘libgdx.badlogicgames.com’ is not trusted.
ERROR: The certificate of ‘libgdx.badlogicgames.com’ doesn't have a known issuer.
The certificate's owner does not match hostname ‘libgdx.badlogicgames.com’
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
/bin/sh: 1: Syntax error: "(" unexpected
/bin/sh: 1: certutil.exe: not found
Building atlas failed. Java not found / unsupported version?
[21:08:52] Finished 'imgres.buildAtlas' after 663 ms
[21:08:52] Starting 'imgres.atlasToJson'...
[21:08:52] 'imgres.atlasToJson' errored after 865 μs
[21:08:52] Error: ENOENT: no such file or directory, scandir '/home/marek/shapez.io/res_built/atlas'
    at readdirSync (node:fs:1456:3)
    at Object.convert (/home/marek/shapez.io/gulp/atlas2json.js:12:22)
    at /home/marek/shapez.io/gulp/image-resources.js:119:21
    at taskWrapper (/home/marek/shapez.io/gulp/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (/home/marek/shapez.io/gulp/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[21:08:52] 'build.dev' errored after 693 ms
[21:08:52] 'main.serveDev' errored after 694 ms
[21:08:52] 'default' errored after 695 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
$ curl -v https://libgdx.badlogicgames.com
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,::1'
* Uses proxy env variable https_proxy == 'http://127.0.0.1:8118/'
*   Trying 127.0.0.1:8118...
* Connected to 127.0.0.1 (127.0.0.1) port 8118 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to libgdx.badlogicgames.com:443
> CONNECT libgdx.badlogicgames.com:443 HTTP/1.1
> Host: libgdx.badlogicgames.com:443
> User-Agent: curl/7.88.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Full build log: 
[build_shapez.txt](https://github.com/tobspr-games/shapez.io/files/13254295/build_shapez.txt)

**Comment by marek22k** [comment]
Workaround:
```
$ rm runnable-texturepacker.jar
$ wget https://libgdx-nightlies.s3.amazonaws.com/libgdx-runnables/runnable-texturepacker.jar
```

**Comment by EmeraldBlock** [comment]
Are you up-to-date? #1423 should've fixed this

**Comment by marek22k** [comment]
The latest release (1.5.1) does not seem to include the fix yet.
```
$ git status
HEAD detached at 1.5.1
nothing to commit, working tree clean
```
```
$ cat gulp/image-resources.js | grep runnableTPSource
const runnableTPSource = "https://libgdx.badlogicgames.com/ci/nightlies/runnables/runnable-texturepacker.jar";
                const safeLink = JSON.stringify(runnableTPSource);
```

**Comment by EmeraldBlock** [comment]
It was fixed after the most recent release, switch to the `master` branch.

If issues tracked the latest release, either they would have to wait to be closed all at once, or every commit would need a release lol

**Comment by EmeraldBlock** [comment]
Duplicate of #1431
