### ISSUE TITLE
Yarn build error

### ISSUE THREAD

**Issue by elbowdonkey** [tobspr-games/shapez.io#1586]
When I try to build the game, I see this error when running `yarn` from the root of the repo:

```
yarn install v1.22.21
warning ../package.json: No license field
error SyntaxError: Invalid value type 993:0 in /Users/me/shapez.io/yarn.lock
    at Parser.unexpected (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:63494:11)
    at Parser.parse (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:63622:16)
    at Parser.parse (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:63599:26)
    at parse (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:63699:21)
    at module.exports.exports.default (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:63261:96)
    at Function.<anonymous> (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:3068:63)
    at Generator.next (<anonymous>)
    at step (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:310:30)
    at /opt/homebrew/lib/node_modules/yarn/lib/cli.js:321:13
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm not familiar enough with `yarn` to know if this is an issue with me using a newer version than what might be known to work or not. How do people typically install and use specific versions of `yarn`?

**Comment by elbowdonkey** [comment]
I think this how you might change the yarn version:

```
yarn policies set-version 1.22.19
```

I chose 1.22.19 since there appear to be other issues where people have said `1.22.19` should work.

Despite that, I still see the error, just less verbose this time:

```
yarn install v1.22.19
warning ../package.json: No license field
error An unexpected error occurred: "Invalid value type 993:0 in /Users/me/shapez.io/yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "/Users/me/shapez.io/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by elbowdonkey** [comment]
I noticed that he `yarn.lock` was modified, so I pulled a clean version, and now, things appear to be building.

```
> git checkout yarn.lock 
> yarn
yarn install v1.22.19
warning ../package.json: No license field
(node:38744) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 44.38s.
```

I'll close for now. Moral of the story for those who run into the same issue: Use yarn 1.22.19, and make sure you have a unmodified `yarn.lock` file.
